### ISSUE TITLE
Aggregate statement fails with Graphql 2.3

### ISSUE THREAD

**Issue by iChebbi** [hschne/graphql-groups#17]
**Problem statement**

Aggregate statement fails when used with lastest version graphql gem. (2.3.18 as of the creation of the issue)

**Proposed solution**

The fix was already implemented by @lemuelbarango (Thanks!) in the fork https://github.com/kweeve/graphql-groups/tree/lb/fix-nil-attributes,
And it seems only collaborators have the permission to create PRs, can anyone of you @hschne @wamcee make this happen?

**Comment by lemuelbarango** [comment]
I've created a PR from my branch. https://github.com/hschne/graphql-groups/pull/18 

Thanks @iChebbi for bringing up this issue
