### ISSUE TITLE
Duplicate type definition found

### ISSUE THREAD

**Issue by sahilchopra** [hschne/graphql-groups#4]
I am getting` Duplicate type definition found `  error at 'Field GroupResultType.groupBy's return type

Duplicate type definition found for name 'MissionFilterItems' at 'Field GroupResultType.groupBy's return type' (France::Groups::MissionFilterItems, France::Groups::MissionFilterItems)
[fff515e1-f141-4ff3-b7c5-f45cd7e3934b] /usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:172:in `visit'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:209:in `visit_field_on_type'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:189:in `block in visit_fields'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:188:in `each'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:188:in `visit_fields'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:147:in `visit'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:209:in `visit_field_on_type'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:189:in `block in visit_fields'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:188:in `each'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:188:in `visit_fields'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:147:in `visit'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:209:in `visit_field_on_type'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:189:in `block in visit_fields'
/usr/local/bundle/gems/graphql-1.11.6/lib/graphql/schema/traversal.rb:188:in `each'

**Comment by hschne** [comment]
Thanks for your bug report! :slightly_smiling_face: 

Before I have a closer look at this, could you confirm that this is unrelated to [this known graphql-ruby issue](https://github.com/rmosolgo/graphql-ruby/issues/935)? Does the problem persist when restarting your server? 

If it does, please provide your type definitions so I can try and reproduce this.
